version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  wkhtmltopdf:
    lang: node-armhf
    handler: ./wkhtmltopdf
    image: tetrash/wkhtmltopdf-node-fn:latest
    environment:
      MAX_JSON_SIZE: '5mb'
