version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  wkhtmltopdf:
    lang: node-armhf
    handler: ./function/handler.js
    image: tetrash/wkhtmltopdf-node-fn:latest
    environment:
      write_timeout: 1m
      read_timeout: 1m
      exec_timeout: 1m
